### ISSUE TITLE
__version__ and repo tag 

### ISSUE THREAD

**Issue by fesaille** [paradoxxxzero/pyls-isort#6]
Hello,

The package on pip is versioned 0.2.0 whereas the lastet tag / `__version__` in `pyls_isort/__about__.py` in `master` is 0.1.1

**Comment by paradoxxxzero** [comment]
Nice catch, I forgot to push...
Should be okay now https://github.com/paradoxxxzero/pyls-isort/releases/tag/0.2.0

**Comment by fesaille** [comment]
perfect, thanks!
