### ISSUE TITLE
Update plugin to use python-lsp-server instead of python-language-server

### ISSUE THREAD

**Issue by andfoy** [paradoxxxzero/pyls-isort#9]
Hi,

Given that Palantir removed all the community maintenance for both python-language-server (pyls) and python-jsonrpc-server (pyls_jsonrpc), we decided to create a separate organization that now maintains a community-based fork for the aforementioned packages, which can be found at: https://github.com/python-lsp/python-lsp-server and https://github.com/python-lsp/python-lsp-jsonrpc.

Our recommendation is to migrate this plugin to be compatible with the community server instead of the Palantir one. In order to do so, here is a migration guide that should help:

1. The plugin should replace `python-language-server` by `python-lsp-server` on its requirements.
2. The `pyls` namespace is now `pylsp`, which means that all `pyls` imports should be replaced by `pylsp`.
3. The `pyls_*` hookspecs are now `pylsp_*` hookspecs.
4. The plugin can preserve the `pyls_` prefix on its namespace in order to prevent further administration and release issues that may arise from renaming it.

Feel free to ask any question about the migration process or about the new community organization for the server.

**Comment by haplo** [comment]
@paradoxxxzero Would you accept a PR that implements these changes if you don't have the time to do it yourself? I'm an user of pyls-isort and would like to keep using it with python-lsp-server.

**Comment by haplo** [comment]
@paradoxxxzero I created a PR that works for me locally. If you could review, merge it and release a new version of `pyls-isort` it would be great.

**Comment by andfoy** [comment]
@haplo, If the maintainer of this repo does not answer by May 18th, would you be willing to be the maintainer for an eventual fork?

**Comment by haplo** [comment]
> @haplo, If the maintainer of this repo does not answer by May 18th, would you be willing to be the maintainer for an eventual fork?

Yes, we can fork to *lsp-isort* and I can maintain it.

**Comment by paradoxxxzero** [comment]
Hello sorry for the delay, I merged the PR and will release a new version very soon

**Comment by haplo** [comment]
> Hello sorry for the delay, I merged the PR and will release a new version very soon

No worries, thank you for looking into this. :+1:
